<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dusun extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dusun_model');
        $this->load->library('form_validation');
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('dusun/create_action'),
	    'id_dusun' => set_value('id_dusun'),
	    'dusun' => set_value('dusun'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'logo_desa' => $this->session->userdata('logo_desa'),
        'titlenav' => 'SIMADES || Data Master',
        'title' => 'Data Master',
        'anchor' => 'Tambah Dusun',
        'isi' => 'dusun/dusun_form',
	);
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('agama/agama_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'dusun' => $this->input->post('dusun',TRUE),
	    );

            $this->Dusun_model->insert($data);
           // $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Dusun_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('dusun/update_action'),
		'id_dusun' => set_value('id_dusun', $row->id_dusun),
		'dusun' => set_value('dusun', $row->dusun),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Dusun',
        'isi' => 'dusun/dusun_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('agama/agama_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_dusun', TRUE));
        } else {
            $data = array(
		'dusun' => $this->input->post('dusun',TRUE),
	    );

            $this->Dusun_model->update($this->input->post('id_dusun', TRUE), $data);
            //$this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Dusun_model->get_by_id($id);

        if ($row) {
            $this->Dusun_model->delete($id);
            //$this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('dusun', 'dusun', 'trim|required');

	$this->form_validation->set_rules('id_dusun', 'id_dusun', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Agama.php */
/* Location: ./application/controllers/Agama.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:44:36 */
/* http://harviacode.com */