<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Goldar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Goldar_model');
        $this->load->library('form_validation');
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('goldar/create_action'),
	    'id_goldar' => set_value('id_goldar'),
	    'goldar' => set_value('goldar'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Tambah Golongan Darah',
        'isi' => 'goldar/goldar_form',
    );
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('goldar/goldar_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'goldar' => $this->input->post('goldar',TRUE),
	    );

            $this->Goldar_model->insert($data);
            //$this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Goldar_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('goldar/update_action'),
		'id_goldar' => set_value('id_goldar', $row->id_goldar),
		'goldar' => set_value('goldar', $row->goldar),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Golongan Darah',
        'isi' => 'goldar/goldar_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('goldar/goldar_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_goldar', TRUE));
        } else {
            $data = array(
		'goldar' => $this->input->post('goldar',TRUE),
	    );

            $this->Goldar_model->update($this->input->post('id_goldar', TRUE), $data);
            //$this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Goldar_model->get_by_id($id);

        if ($row) {
            $this->Goldar_model->delete($id);
            //$this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('goldar', 'goldar', 'trim|required');

	$this->form_validation->set_rules('id_goldar', 'id_goldar', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Goldar.php */
/* Location: ./application/controllers/Goldar.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:44:45 */
/* http://harviacode.com */