<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hubkel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hubkel_model');
        $this->load->library('form_validation');
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('hubkel/create_action'),
	    'id_hubkel' => set_value('id_hubkel'),
	    'hubkel' => set_value('hubkel'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Tambah Hubungan Keluarga',
        'isi' => 'hubkel/hubkel_form',
    );
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('hubkel/hubkel_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'hubkel' => $this->input->post('hubkel',TRUE),
	    );

            $this->Hubkel_model->insert($data);
           // $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Hubkel_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('hubkel/update_action'),
		'id_hubkel' => set_value('id_hubkel', $row->id_hubkel),
		'hubkel' => set_value('hubkel', $row->hubkel),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Hubungan Keluarga',
        'isi' => 'hubkel/hubkel_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('hubkel/hubkel_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_hubkel', TRUE));
        } else {
            $data = array(
		'hubkel' => $this->input->post('hubkel',TRUE),
	    );

            $this->Hubkel_model->update($this->input->post('id_hubkel', TRUE), $data);
           // $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Hubkel_model->get_by_id($id);

        if ($row) {
            $this->Hubkel_model->delete($id);
           // $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('hubkel', 'hubkel', 'trim|required');

	$this->form_validation->set_rules('id_hubkel', 'id_hubkel', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Hubkel.php */
/* Location: ./application/controllers/Hubkel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:44:52 */
/* http://harviacode.com */