<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_surat extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenis_surat_model');
        $this->load->library('form_validation');
    }

    

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('jenis_surat/create_action'),
	    'id_jenis' => set_value('id_jenis'),
	    'jenis_surat' => set_value('jenis_surat'),
	    'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'logo_desa' => $this->session->userdata('logo_desa'),
        'titlenav' => 'SIMADES || Data Master',
        'title' => 'Data Master',
        'anchor' => 'Tambah Jenis Surat',
        'isi' => 'jenis_surat/jenis_surat_form',
    );
        $this->load->view('layout/wrapper', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'jenis_surat' => $this->input->post('jenis_surat',TRUE),
	    );

            $this->Jenis_surat_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenis_surat/create'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jenis_surat_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('jenis_surat/update_action'),
		'id_jenis' => set_value('id_jenis', $row->id_jenis),
		'jenis_surat' => set_value('jenis_surat', $row->jenis_surat),
	    'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'logo_desa' => $this->session->userdata('logo_desa'),
        'titlenav' => 'SIMADES || Data Master',
        'title' => 'Data Master',
        'anchor' => 'Edit Jenis Surat',
        'isi' => 'jenis_surat/jenis_surat_form',
            );
                $this->load->view('layout/wrapper', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jenis', TRUE));
        } else {
            $data = array(
		'jenis_surat' => $this->input->post('jenis_surat',TRUE),
	    );

            $this->Jenis_surat_model->update($this->input->post('id_jenis', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    
    public function _rules() 
    {
	$this->form_validation->set_rules('jenis_surat', 'jenis surat', 'trim|required');

	$this->form_validation->set_rules('id_jenis', 'id_jenis', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jenis_surat.php */
/* Location: ./application/controllers/Jenis_surat.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-16 05:45:47 */
/* http://harviacode.com */