<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kerja extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kerja_model');
        $this->load->library('form_validation');
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('kerja/create_action'),
	    'id_kerja' => set_value('id_kerja'),
	    'kerja' => set_value('kerja'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Tambah Pekerjaan',
        'isi' => 'kerja/kerja_form',
    );
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('kerja/kerja_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kerja' => $this->input->post('kerja',TRUE),
	    );

            $this->Kerja_model->insert($data);
            //$this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kerja_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('kerja/update_action'),
		'id_kerja' => set_value('id_kerja', $row->id_kerja),
		'kerja' => set_value('kerja', $row->kerja),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Pekerjaan',
        'isi' => 'kerja/kerja_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('kerja/kerja_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kerja', TRUE));
        } else {
            $data = array(
		'kerja' => $this->input->post('kerja',TRUE),
	    );

            $this->Kerja_model->update($this->input->post('id_kerja', TRUE), $data);
            //$this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kerja_model->get_by_id($id);

        if ($row) {
            $this->Kerja_model->delete($id);
            //$this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kerja', 'kerja', 'trim|required');

	$this->form_validation->set_rules('id_kerja', 'id_kerja', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kerja.php */
/* Location: ./application/controllers/Kerja.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:45:12 */
/* http://harviacode.com */