<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Agama_model');
        $this->load->model('Dusun_model');
        $this->load->model('Goldar_model');
        $this->load->model('Hubkel_model');
        $this->load->model('Kerja_model');
        $this->load->model('Pendidikan_model');
        $this->load->model('Status_kawin_model');
        $this->load->model('Jabatan_model');
        $this->load->model('Jenis_surat_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        
        $agama = $this->Agama_model->get_all();
        $dusun = $this->Dusun_model->get_all();
        $goldar = $this->Goldar_model->get_all();
        $hubkel = $this->Hubkel_model->get_all();
        $kerja = $this->Kerja_model->get_all();
        $pendidikan = $this->Pendidikan_model->get_all();
        $stkawin = $this->Status_kawin_model->get_all();
        $jabatan = $this->Jabatan_model->get_all();
        $jenis_surat = $this->Jenis_surat_model->get_all();
        
        $data = array(
            'agama_data' => $agama,
            'dusun_data' => $dusun,
            'goldar_data' => $goldar,
            'hubkel_data' => $hubkel,
            'kerja_data' => $kerja,
            'pendidikan_data' => $pendidikan,
            'status_kawin_data' => $stkawin,
            'jabatan_data' => $jabatan,
            'jenis_surat_data' => $jenis_surat,
            'id_user' => $this->session->userdata('id_user'),
            'nama_user' => $this->session->userdata('nama_user'),
            'jabatan' => $this->session->userdata('jabatan'),
            'nama_desa' => $this->session->userdata('nama_desa'),
            'titlenav' => 'SIMADES || Data Master',
            'title' => 'Data Master',
            'anchor' => 'Data Master',
            'isi' => 'datamaster',
        );
        $this->load->view('layout/wrapper', $data);
        

        //$this->template->display('datamaster', $data);
    }

    
    

}

/* End of file Agama.php */
/* Location: ./application/controllers/Agama.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:44:36 */
/* http://harviacode.com */