<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendidikan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pendidikan_model');
        $this->load->library('form_validation');
    }
 
    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('pendidikan/create_action'),
	    'id_pendidikan' => set_value('id_pendidikan'),
	    'pendidikan' => set_value('pendidikan'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Tambah Pendidikan',
        'isi' => 'pendidikan/pendidikan_form',
    );
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('pendidikan/pendidikan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'pendidikan' => $this->input->post('pendidikan',TRUE),
	    );

            $this->Pendidikan_model->insert($data);
            //$this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pendidikan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('pendidikan/update_action'),
		'id_pendidikan' => set_value('id_pendidikan', $row->id_pendidikan),
		'pendidikan' => set_value('pendidikan', $row->pendidikan),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Pendidikan',
        'isi' => 'pendidikan/pendidikan_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('pendidikan/pendidikan_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_pendidikan', TRUE));
        } else {
            $data = array(
		'pendidikan' => $this->input->post('pendidikan',TRUE),
	    );

            $this->Pendidikan_model->update($this->input->post('id_pendidikan', TRUE), $data);
            //$this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pendidikan_model->get_by_id($id);

        if ($row) {
            $this->Pendidikan_model->delete($id);
            //$this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('pendidikan', 'pendidikan', 'trim|required');

	$this->form_validation->set_rules('id_pendidikan', 'id_pendidikan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pendidikan.php */
/* Location: ./application/controllers/Pendidikan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 16:45:21 */
/* http://harviacode.com */