<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status_kawin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_kawin_model');
        $this->load->library('form_validation');
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => site_url('status_kawin/create_action'),
	    'id_stkawin' => set_value('id_stkawin'),
	    'stkawin' => set_value('stkawin'),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Tambah Status Perkawinan',
        'isi' => 'status_kawin/status_kawin_form',
    );
        $this->load->view('layout/wrapper', $data);
        //$this->template->display('status_kawin/status_kawin_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'stkawin' => $this->input->post('stkawin',TRUE),
	    );

            $this->Status_kawin_model->insert($data);
            //$this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Status_kawin_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Edit',
                'action' => site_url('status_kawin/update_action'),
		'id_stkawin' => set_value('id_stkawin', $row->id_stkawin),
		'stkawin' => set_value('stkawin', $row->stkawin),
        'id_user' => $this->session->userdata('id_user'),
        'nama_user' => $this->session->userdata('nama_user'),
        'jabatan' => $this->session->userdata('jabatan'),
        'nama_desa' => $this->session->userdata('nama_desa'),
        'titlenav' => 'SIMADES || Data Master',
	    'title' => 'Data Master',
        'anchor' => 'Edit Status Perkawinan',
        'isi' => 'status_kawin/status_kawin_form',
        );
            $this->load->view('layout/wrapper', $data);
            //$this->template->display('status_kawin/status_kawin_form', $data);
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_stkawin', TRUE));
        } else {
            $data = array(
		'stkawin' => $this->input->post('stkawin',TRUE),
	    );

            $this->Status_kawin_model->update($this->input->post('id_stkawin', TRUE), $data);
            //$this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('master'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Status_kawin_model->get_by_id($id);

        if ($row) {
            $this->Status_kawin_model->delete($id);
            //$this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('master'));
        } else {
            //$this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('master'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('stkawin', 'stkawin', 'trim|required');

	$this->form_validation->set_rules('id_stkawin', 'id_stkawin', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Status_kawin.php */
/* Location: ./application/controllers/Status_kawin.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-10 07:51:42 */
/* http://harviacode.com */