<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kedatangan_model extends CI_Model
{

    public $table = 'kedatangan';
    public $id = 'id_datang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('penduduk','kedatangan.nik_pendatang = penduduk.nik');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_nokk_asal($nokk)
    {
        $this->db->where('no_kk_asal', $nokk);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_datang', $q);
	$this->db->or_like('nik_pendatang', $q);
	$this->db->or_like('alamat_asal', $q);
	$this->db->or_like('alasan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $c=NULL, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        if($c){
            $this->db->like($c, $q);
        }
    $this->db->join('penduduk','kedatangan.nik_pendatang = penduduk.nik');
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kedatangan_model.php */
/* Location: ./application/models/Kedatangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-16 05:46:01 */
/* http://harviacode.com */