<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelahiran_model extends CI_Model
{

    public $table = 'kelahiran';
    public $id = 'id_lahir';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_lahir', $q);
	$this->db->or_like('nis_bayi', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('tpt_lahir', $q);
	$this->db->or_like('jekel', $q);
	$this->db->or_like('berat_bayi', $q);
	$this->db->or_like('anak_ke', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('panjang_bayi', $q);
	$this->db->or_like('nik_ayah', $q);
	$this->db->or_like('nik_ibu', $q);
	$this->db->or_like('nik_saksi1', $q);
	$this->db->or_like('nik_saksi2', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $c=NULL, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        if($c){
            $this->db->like($c, $q);
        }
	
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kelahiran_model.php */
/* Location: ./application/models/Kelahiran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-16 05:46:08 */
/* http://harviacode.com */