<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kepergian_model extends CI_Model
{

    public $table = 'kepergian';
    public $id = 'id_pergi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
        return $this->db->get($this->table)->result();
    }

    function get_pengikut($nik, $no_kk)
    {
        $this->db->order_by('penduduk.id_hubkel', 'ASC');
        $this->db->where('kepergian.pengikut', 'Keluarga');
        //$this->db->where_not_in('penduduk.hubkel', 'Kepala Keluarga');
        $this->db->where_not_in('nik', $nik);
        $this->db->where('penduduk.no_kk', $no_kk);

        $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
        $this->db->join('agama','penduduk.id_agama = agama.id_agama');
        $this->db->join('kerja','penduduk.id_kerja = kerja.id_kerja');
        $this->db->join('pendidikan','penduduk.id_agama = pendidikan.id_pendidikan');
        $this->db->join('status_kawin','penduduk.id_stskawin = status_kawin.id_stkawin');
        
        //$this->db->join('hubkel','penduduk.id_hubkel = hubkel.id_hubkel');
        return $this->db->get($this->table)->result();
    }

    function jml_pengikut($nik, $no_kk)
    {
        $this->db->order_by('penduduk.id_hubkel', 'ASC');
        $this->db->where('kepergian.pengikut', 'Keluarga');
        //$this->db->where_not_in('penduduk.hubkel', 'Kepala Keluarga');
        $this->db->where_not_in('nik', $nik);
        $this->db->where('penduduk.no_kk', $no_kk);

        $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
        //$this->db->join('hubkel','penduduk.id_hubkel = hubkel.id_hubkel');
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
        $this->db->join('kk','penduduk.no_kk = kk.no_kk');
        return $this->db->get($this->table)->row();
    }

    function get_by_nik($id)
    {
        $this->db->where('nik_pergi', $id);
        $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
        $this->db->join('agama','penduduk.id_agama = agama.id_agama');
        $this->db->join('kerja','penduduk.id_kerja = kerja.id_kerja');
        $this->db->join('pendidikan','penduduk.id_agama = pendidikan.id_pendidikan');
        $this->db->join('status_kawin','penduduk.id_stskawin = status_kawin.id_stkawin');
        $this->db->join('kk','penduduk.no_kk = kk.no_kk');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pergi', $q);
	$this->db->or_like('nik_pergi', $q);
	$this->db->or_like('alamat_tuju', $q);
	$this->db->or_like('alasan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $c=NULL, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        if($c){
            $this->db->like($c, $q);
        }
    $this->db->join('penduduk','kepergian.nik_pergi = penduduk.nik');
    $this->db->join('agama','penduduk.id_agama = agama.id_agama');
    $this->db->join('kerja','penduduk.id_kerja = kerja.id_kerja');
    $this->db->join('kk','penduduk.no_kk = kk.no_kk');
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kepergian_model.php */
/* Location: ./application/models/Kepergian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-16 05:46:20 */
/* http://harviacode.com */