<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kk_model extends CI_Model
{

    public $table = 'kk';
    public $id = 'no_kk';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_number($id)
    {
      $this->db->select('no_kk');
      $this->db->where('no_kk',$id);
      return $this->db->get('kk')->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_kk', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('rt', $q);
	$this->db->or_like('rw', $q);
	$this->db->or_like('kelurahan', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('propinsi', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_kk', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('rt', $q);
	$this->db->or_like('rw', $q);
	$this->db->or_like('kelurahan', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('propinsi', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kk_model.php */
/* Location: ./application/models/Kk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-03 12:39:49 */
/* http://harviacode.com */
