<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Memiliki_jabatan_model extends CI_Model
{

    public $table = 'memiliki_jabatan';
    public $id = 'id_memiliki';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('jabatan','jabatan.id_jabatan = memiliki_jabatan.id_jabatan');
        return $this->db->get($this->table)->result();
    }

  
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Layanan_model.php */
/* Location: ./application/models/Layanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-16 05:46:29 */
/* http://harviacode.com */